---
--- Generated by Luanalysis
--- Created by t.
--- DateTime: 2024/7/11 21:49
---
local key = KEYS[1]
local threadId = ARGV[1]
local id = redis.call('GET', key)
if(id == threadId) then
    return redis.call('DEL', key)
end
return 0
